portal_page: "http://test3-blizko.ru"
normal_user_mail: "crow1@gmail.com"
normal_user_pwd: "0000"
super_user_mail: "sunlf@yandex.ru"
super_user_pwd: "82718951"

cell_phone_number: "89001234567"
company_name: "CrowFarm"
company_user_name: "Vasiliy"
company_about: "Crow Farm"
company_code: "123"
company_phone_number: "1234567"